[package]
name = "sbi-rt"
version = "0.0.1"
edition = "2021"
description = "Runtime library for supervisors to call RISC-V Supervisor Binary Interface (RISC-V SBI)"
categories = ["os", "no-std"]
keywords = ["riscv", "sbi", "rustsbi"]
authors = ["YdrMaster <ydrml@hotmail.com>", "Luo Jia <me@luojia.cc>"]
repository = "https://github.com/rustsbi/sbi-rt"
documentation = "https://docs.rs/sbi-rt"
license = "MulanPSL-2.0 OR MIT"
readme = "README.md"

[dependencies]
sbi-spec = { path = "../sbi-spec" }
