language: rust
matrix:
  include:
    # Minimal supported rustc version
    - rust: 1.24.0
      script:
        # Build only the library (examples are allowed to fail)
        - cargo build
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly-2018-03-07
      script:
        # nostd build
        - cargo build --no-default-features --features core_io

  allow_failures:
    - rust: nightly
